#! /bin/sh

compton -b --config /home/liam/.config/compton.conf
sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor LVDS-1 -d 1 2 3 4 5

bspc config border_width          0
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config click-to-focus        true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a xfce4-terminal desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a emacs desktop='^3'
bspc rule -a evince desktop='^4'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

feh --bg-fill /usr/share/xfce4/backdrops/Mountainous_View_by_Sven_Scheuermeier.jpg
polybar top

# https://wiki.archlinux.org/index.php/Cursor_themes#Change_X_shaped_default_cursor
xsetroot -cursor_name left_ptr

# https://www.reddit.com/r/bspwm/comments/2mpui3/attempting_to_autostart_a_few_programs/
# launch programs
/home/liam/.config/bspwm/launch.sh
